### ISSUE TITLE
Anyone aware of how to get myq-node to work in Node-RED using node-red-contrib-npm?

### ISSUE THREAD

**Issue by jtmoderate876** [ConnorTheFox/myq-node#1]
Anyone aware of how to get myq-node to work in Node-RED using ?
I seem to be able to execute login but not getDevices()
I get payload: "[Circular ~]"
instead of a list of devices.

I do this from Node-RED, using node-red-contrib-npm,

![image](https://user-images.githubusercontent.com/16329872/28339524-f9641048-6bd1-11e7-8d56-aed140c63e96.png)

then create function: "establish function getDevices":
```
const getDevices = function () {
    
    let promise = new Promise((resolve, reject) => {
        msg.resolve = resolve;
        msg.reject = reject;
    });
    
    node.send(Object.assign({}, msg));
    
    return promise;
};

global.set('getDevices', getDevices);

```
that feeds the NPM node pointing to npm node: myq-node
```
msg.payload = npm_module.getDevices();
return msg;

```

**Comment by JustAnOpossum** [comment]
I don't know node RED but this is what getDevices returns

```
{ Devices: [], ReturnCode: '0', ErrorMessage: '', CorrelationId: '' }
```

**Comment by jtmoderate876** [comment]
Closing but I never got it working with NodeRED.
May revisit if things change or Chamberlain becomes more open.
Thx.
