### ISSUE TITLE
Where does the application ID come from?

### ISSUE THREAD

**Issue by Ne0nx3r0** [ConnorTheFox/myq-node#3]
I saw it is:

OA9I/hgmPHFp9RYKJqCKfwnhh28uqLJzZ9KOJf1DXoo8N2XAaVX6A1wcLYyWsnnv

Am I supposed to generate my own? What does this value represent?

**Comment by JustAnOpossum** [comment]
No, you should just be able to leave that alone, I don't know exactly what it represents since there is no API documentation and it was on the HTTP request. Since the way I found out how to use the API was a packet sniffer on my phone.

**Comment by Ne0nx3r0** [comment]
Ah that makes sense, thanks!

I guess the app id is generated for the user account or device or something. You can't seem to just put anything there but neither could I find where to create one.

**Comment by JustAnOpossum** [comment]
I don't believe it is dependent on the account since in the myq python library they use the same ID. I think it is the ID for chamberlain garage door openers.
